# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-04 01:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vp_web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cverification',
            name='stimulus_dual',
        ),
        migrations.RemoveField(
            model_name='cverification',
            name='stimulus_dual_exist',
        ),
        migrations.RemoveField(
            model_name='cverification',
            name='stimulus_single',
        ),
        migrations.AddField(
            model_name='cverification',
            name='stimulus',
            field=models.CharField(blank=True, max_length=500, verbose_name='Stimulus'),
        ),
        migrations.AddField(
            model_name='cverification',
            name='stimulus_other',
            field=models.CharField(blank=True, max_length=500, verbose_name='Stimulus_other'),
        ),
        migrations.AddField(
            model_name='cverification',
            name='stimulus_other_exist',
            field=models.BooleanField(default=False, verbose_name='Stimulus other exist status'),
        ),
    ]
