# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-02 16:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vp_web', '0002_auto_20180204_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='cverification',
            name='coverage',
            field=models.CharField(blank=True, default='fill your cover sva file name', max_length=500, verbose_name='Coverage'),
        ),
        migrations.AddField(
            model_name='cverification',
            name='coverage_description',
            field=models.TextField(default='', max_length=1000, verbose_name='coverage_description'),
        ),
        migrations.AddField(
            model_name='cverification',
            name='coverage_exist',
            field=models.BooleanField(default=False, verbose_name='Cover sva exist status'),
        ),
        migrations.AddField(
            model_name='cverification',
            name='coverage_owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Coverage_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
