# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-02 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vp_web', '0003_auto_20180502_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cverification',
            name='vrg_register_status',
        ),
        migrations.AddField(
            model_name='cverification',
            name='into_regression',
            field=models.CharField(blank=True, choices=[('NO', 'not in regression'), ('RD', 'has in regression')], default='NO', max_length=2),
        ),
    ]
