# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-02 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vp_web', '0004_auto_20180502_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='cverification',
            name='coverage_status',
            field=models.CharField(blank=True, choices=[('0', '0%'), ('1', '10%'), ('2', '20%'), ('3', '30%'), ('4', '40%'), ('5', '50%'), ('6', '60%'), ('7', '70%'), ('8', '80%'), ('9', '90%'), ('10', '100%'), ('DO', 'closed')], default='0', max_length=2),
        ),
    ]
