# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-20 05:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TBaseItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(default='', max_length=20, verbose_name='project')),
                ('check_item', models.CharField(default='', max_length=20, verbose_name='check_item')),
                ('partition', models.CharField(default='', max_length=20, verbose_name='partition')),
                ('stage', models.CharField(default='R0', max_length=20, verbose_name='stage')),
                ('vio_total_number', models.CharField(default='', max_length=10, verbose_name='vio total number')),
                ('corner', models.CharField(default='-', max_length=20, verbose_name='corner')),
                ('fn', models.CharField(default='-', max_length=20, verbose_name='fn')),
                ('signoff_mode', models.CharField(default='-', max_length=20, verbose_name='signoff_mode')),
                ('check_mode', models.CharField(default='-', max_length=20, verbose_name='check_mode')),
                ('database_version', models.CharField(default='-', max_length=50, verbose_name='database version')),
                ('database_date', models.CharField(default='-', max_length=50, verbose_name='database date')),
                ('summit_time', models.CharField(default='', max_length=40, verbose_name='summit time')),
                ('redundent', models.CharField(max_length=100, verbose_name='redundent')),
                ('log', models.CharField(default='-', max_length=300, verbose_name='log')),
                ('setup_wns', models.CharField(default='-', max_length=20, verbose_name='Setup WNS')),
                ('setup_tns', models.CharField(default='-', max_length=20, verbose_name='Setup TNS')),
                ('setup_nvp', models.CharField(default='-', max_length=20, verbose_name='Setup NVP')),
                ('hold_wns', models.CharField(default='-', max_length=20, verbose_name='Hold WNS')),
                ('hold_tns', models.CharField(default='-', max_length=20, verbose_name='Hold TNS')),
                ('hold_nvp', models.CharField(default='-', max_length=20, verbose_name='Hold NVP')),
            ],
        ),
        migrations.CreateModel(
            name='TCheckCase',
            fields=[
                ('tbaseitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='signoff_check.TBaseItem')),
                ('check', models.CharField(default='-', max_length=40, verbose_name='Check')),
                ('status', models.CharField(default='-', max_length=20, verbose_name='Status')),
                ('log_path', models.CharField(default='-', max_length=500, verbose_name='log path')),
                ('comment', models.TextField(default='-', max_length=500)),
                ('check_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='check_owner', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('signoff_check.tbaseitem',),
        ),
        migrations.CreateModel(
            name='TOwnerCase',
            fields=[
                ('tbaseitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='signoff_check.TBaseItem')),
                ('owner', models.CharField(default='-', max_length=20, verbose_name='Owner')),
                ('wns', models.CharField(default='-', max_length=20, verbose_name='WNS')),
                ('tns', models.CharField(default='-', max_length=20, verbose_name='TNS')),
                ('nvp', models.CharField(default='-', max_length=20, verbose_name='NVP')),
                ('freq', models.CharField(default='-', max_length=20, verbose_name='FREQ')),
                ('wns_h', models.CharField(default='-', max_length=20, verbose_name='WNS(H)')),
                ('tns_h', models.CharField(default='-', max_length=20, verbose_name='TNS(H)')),
                ('nvp_h', models.CharField(default='-', max_length=20, verbose_name='NVP(H)')),
                ('type', models.CharField(default='-', max_length=20, verbose_name='type')),
                ('log_path', models.CharField(default='-', max_length=500, verbose_name='log path')),
            ],
            bases=('signoff_check.tbaseitem',),
        ),
        migrations.CreateModel(
            name='TPathGroup',
            fields=[
                ('tbaseitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='signoff_check.TBaseItem')),
                ('group', models.CharField(default='-', max_length=50, verbose_name='Path Group')),
                ('wns', models.CharField(default='-', max_length=20, verbose_name='WNS')),
                ('tns', models.CharField(default='-', max_length=20, verbose_name='TNS')),
                ('nvp', models.CharField(default='-', max_length=20, verbose_name='NVP')),
                ('freq', models.CharField(default='-', max_length=20, verbose_name='FREQ')),
                ('wns_h', models.CharField(default='-', max_length=20, verbose_name='WNS(H)')),
                ('tns_h', models.CharField(default='-', max_length=20, verbose_name='TNS(H)')),
                ('nvp_h', models.CharField(default='-', max_length=20, verbose_name='NVP(H)')),
                ('type', models.CharField(default='-', max_length=20, verbose_name='type')),
                ('log_path', models.CharField(default='-', max_length=500, verbose_name='log path')),
            ],
            bases=('signoff_check.tbaseitem',),
        ),
    ]
