# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-04 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release_check', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseitem',
            name='fail_owner_count',
            field=models.CharField(default='', max_length=20, verbose_name='fail_owner_count'),
        ),
    ]
