# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-04 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release_check', '0002_baseitem_fail_owner_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseitem',
            name='design_git_number',
            field=models.CharField(default='', max_length=50, verbose_name='design_git_number'),
        ),
    ]
