# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-22 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release_check', '0003_auto_20180104_0258'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownercase',
            name='info_number',
            field=models.CharField(default='', max_length=20, verbose_name='info_number'),
        ),
        migrations.AddField(
            model_name='ownercase',
            name='warn_number',
            field=models.CharField(default='', max_length=20, verbose_name='warn_number'),
        ),
    ]
