# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-24 23:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('release_check', '0004_auto_20180522_0728'),
    ]

    operations = [
        migrations.CreateModel(
            name='case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_type', models.CharField(default='', max_length=20, verbose_name='case_type')),
                ('case_num', models.CharField(default='', max_length=5, verbose_name='case_num')),
                ('link', models.CharField(default='', max_length=150, verbose_name='link')),
            ],
        ),
        migrations.CreateModel(
            name='unit',
            fields=[
                ('key', models.CharField(default='', max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='key')),
                ('val', models.CharField(default='', max_length=20, verbose_name='val')),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='c1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='release_check.unit'),
        ),
    ]
