# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-24 23:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('release_check', '0005_auto_20180524_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='c2',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='c2', to='release_check.unit'),
        ),
    ]
