# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-24 23:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('release_check', '0006_case_c2'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='c3',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='c3', to='release_check.unit'),
        ),
        migrations.AddField(
            model_name='case',
            name='c4',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='c4', to='release_check.unit'),
        ),
        migrations.AddField(
            model_name='case',
            name='c5',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='c5', to='release_check.unit'),
        ),
    ]
