# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-26 13:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('release_check', '0007_auto_20180524_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='c1',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='c1', to='release_check.unit'),
        ),
    ]
