# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-26 13:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('release_check', '0008_auto_20180526_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='case_old',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_type', models.CharField(default='', max_length=20, verbose_name='case_type')),
                ('case_num', models.CharField(default='', max_length=5, verbose_name='case_num')),
                ('link', models.CharField(default='', max_length=150, verbose_name='link')),
                ('c1', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='c1', to='release_check.unit')),
                ('c2', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='c2', to='release_check.unit')),
                ('c3', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='c3', to='release_check.unit')),
                ('c4', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='c4', to='release_check.unit')),
                ('c5', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='c5', to='release_check.unit')),
            ],
        ),
        migrations.RemoveField(
            model_name='case',
            name='c1',
        ),
        migrations.RemoveField(
            model_name='case',
            name='c2',
        ),
        migrations.RemoveField(
            model_name='case',
            name='c3',
        ),
        migrations.RemoveField(
            model_name='case',
            name='c4',
        ),
        migrations.RemoveField(
            model_name='case',
            name='c5',
        ),
        migrations.AddField(
            model_name='case',
            name='c1_key',
            field=models.CharField(default='', max_length=30, verbose_name='c1_key'),
        ),
        migrations.AddField(
            model_name='case',
            name='c1_val',
            field=models.CharField(default='', max_length=30, verbose_name='c1_val'),
        ),
        migrations.AddField(
            model_name='case',
            name='c2_key',
            field=models.CharField(default='', max_length=30, verbose_name='c2_key'),
        ),
        migrations.AddField(
            model_name='case',
            name='c2_val',
            field=models.CharField(default='', max_length=30, verbose_name='c2_val'),
        ),
        migrations.AddField(
            model_name='case',
            name='c3_key',
            field=models.CharField(default='', max_length=30, verbose_name='c3_key'),
        ),
        migrations.AddField(
            model_name='case',
            name='c3_val',
            field=models.CharField(default='', max_length=30, verbose_name='c3_val'),
        ),
        migrations.AddField(
            model_name='case',
            name='c4_key',
            field=models.CharField(default='', max_length=30, verbose_name='c4_key'),
        ),
        migrations.AddField(
            model_name='case',
            name='c4_val',
            field=models.CharField(default='', max_length=30, verbose_name='c4_val'),
        ),
        migrations.AddField(
            model_name='case',
            name='c5_key',
            field=models.CharField(default='', max_length=30, verbose_name='c5_key'),
        ),
        migrations.AddField(
            model_name='case',
            name='c5_val',
            field=models.CharField(default='', max_length=30, verbose_name='c5_val'),
        ),
    ]
