# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-26 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release_check', '0009_auto_20180526_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='c6_key',
            field=models.CharField(default='', max_length=30, verbose_name='c6_key'),
        ),
        migrations.AddField(
            model_name='case',
            name='c6_val',
            field=models.CharField(default='', max_length=30, verbose_name='c6_val'),
        ),
    ]
