# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-26 16:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('release_check', '0010_auto_20180526_1504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='case_num',
            new_name='column_num',
        ),
    ]
