# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-26 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release_check', '0011_auto_20180526_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='table_title',
            field=models.CharField(default='', max_length=50, verbose_name='table_title'),
        ),
        migrations.AlterField(
            model_name='case',
            name='case_type',
            field=models.CharField(default='', max_length=30, verbose_name='case_type'),
        ),
    ]
