# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-26 19:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('release_check', '0012_auto_20180526_1634'),
    ]

    operations = [
        migrations.DeleteModel(
            name='case',
        ),
    ]
