# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-26 19:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('release_check', '0013_delete_case'),
    ]

    operations = [
        migrations.CreateModel(
            name='case',
            fields=[
                ('baseitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='release_check.BaseItem')),
                ('table_title', models.CharField(default='', max_length=50, verbose_name='table_title')),
                ('table_order', models.CharField(default='', max_length=50, verbose_name='table_order')),
                ('case_type', models.CharField(default='', max_length=30, verbose_name='case_type')),
                ('column_num', models.CharField(default='', max_length=5, verbose_name='case_num')),
                ('c1_key', models.CharField(default='', max_length=30, verbose_name='c1_key')),
                ('c1_val', models.CharField(default='', max_length=30, verbose_name='c1_val')),
                ('c2_key', models.CharField(default='', max_length=30, verbose_name='c2_key')),
                ('c2_val', models.CharField(default='', max_length=30, verbose_name='c2_val')),
                ('c3_key', models.CharField(default='', max_length=30, verbose_name='c3_key')),
                ('c3_val', models.CharField(default='', max_length=30, verbose_name='c3_val')),
                ('c4_key', models.CharField(default='', max_length=30, verbose_name='c4_key')),
                ('c4_val', models.CharField(default='', max_length=30, verbose_name='c4_val')),
                ('c5_key', models.CharField(default='', max_length=30, verbose_name='c5_key')),
                ('c5_val', models.CharField(default='', max_length=30, verbose_name='c5_val')),
                ('c6_key', models.CharField(default='', max_length=30, verbose_name='c6_key')),
                ('c6_val', models.CharField(default='', max_length=30, verbose_name='c6_val')),
                ('link', models.CharField(default='', max_length=150, verbose_name='link')),
            ],
            bases=('release_check.baseitem',),
        ),
    ]
